Progress Report - March 2022
yuzu-emu/yuzu-emu.github.io pull request #314
Opened 2022-04-03 08:47 UTC by goldenx86

3 years, baby!

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +	"./kirbyvram.png| PC requirements: RTX 3090? Not on our watch!"
Vram PR may be closed bc of regressions it causes in other titles. Can you advise users to check out the mods for this game? Particularly the disable dynamic res mod.

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +This is caused because neither the Windows AMD drivers nor any of the Linux options offer support for the `VK_EXT_vertex_input_dynamic_state` extension, which helps reduce the shader count by 3 times
RADV does support the extension, but it's blacklisted on RDNA2 hardware bc it causes crashes there. (See last month's progress report ;) )

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Intel and Nvidia hardware do offer support and enjoy a much reduced shader count, and the associated reduced stuttering when building their cache.
Intel windows is blacklisted as well iirc :P

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +NVFlinger is the service in charge of presenting to the display, so any improvement in this area will bring more even frametimes, perceived as less stuttering even when the frame rate count stays at
```suggestion
NVFlinger is the service in charge of presenting to the display, so any improvement in this area will bring more stable frametimes, perceived as less stuttering even when the frame rate count stays at a solid 60 FPS.
```

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Our original implementation was basically guessing done back in 2018, it was lacking in *several* areas.
```suggestion
Our original implementation was basically guess work done back in 2018, it was lacking in *several* areas.
```

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +By simply {{< gh-hovercard "8066" "disabling this check" >}}, Windows builds can again enjoy the extra performance gained from decoding via GPU.
```suggestion
By simply {{< gh-hovercard "8066" "disabling this check on Windows" >}}, Windows builds can again enjoy the extra performance gained from decoding via GPU.
```
or some other rewording to make it not seem like the check was removed and Linux Flatpack builds regressed.

2022-04-04 03:25 UTC, ameerj commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +epicboy found out that {{< gh-hovercard "8106" "avoiding a thread lock" >}} allows Extreme GPU accuracy to be more stable, making it a safe option for those aiming for the most possible accurate rend
```suggestion
epicboy found out that {{< gh-hovercard "8106" "avoiding a doubly locked mutex" >}} fixes a crash when using Extreme GPU accuracy on the OpenGL backend, making it a safe option for those aiming for the most possible accurate rendering.
```

2022-04-10 02:20 UTC, Schplee requested changes

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +If video playing feels smoother, you now know the reason! Thanks epicboy!
```suggestion
If video playback feels smoother, you now know the reason! Thanks epicboy!
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Changing the behaviour of how yuzu handles both GPU instance creation and rendering instance creation helps avoid direct to desktop crashes caused by outdated drivers or broken Vulkan injectors.
```suggestion
Changing the behaviour of how yuzu handles both GPU instance creation and rendering instance creation helps avoid direct-to-desktop crashes caused by outdated drivers or broken Vulkan injectors.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +He also includes an {{< gh-hovercard "8068" "optimization focused on eliminating `if(false) …` branches on the shader code" >}}.
```suggestion
He also includes an {{< gh-hovercard "8068" "optimization focused on eliminating `if(false) {…}` branches in the shader code" >}}. 
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +In an effort to reduce RAM use on yuzu, Merry tested {{< gh-hovercard "8016" "reducing the size of the code caches" >}} in dynarmic.
```suggestion
In an effort to reduce RAM use in yuzu, Merry tested {{< gh-hovercard "8016" "reducing the size of the code caches" >}} in dynarmic.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Once the result went live, users started to complain, reports of sudden stuttering affecting `Super Smash Bros. Ultimate` were on all communication channels.
```suggestion
Once the result went live, users started to complain, reports of sudden stuttering affecting `Super Smash Bros. Ultimate` were in all communication channels.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Morph also has worked on `MiiEdit` the applet for Mii creation that [german77](https://github.com/german77) started working on last month.
```suggestion
Morph also worked on `MiiEdit`, the applet for Mii creation that [german77](https://github.com/german77) started working on last month.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +It’s like the Hydra, you cut one head, two new ones show up.
```suggestion
It’s like the Hydra, you cut off one head and two new heads appear.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +toastUnlimited gave us a simple but really important QoL change, {{< gh-hovercard "8035" "disabling the `Web Applet` by default" >}}.
```suggestion
toastUnlimited gave us a simple, but really important, quality of life change, {{< gh-hovercard "8035" "disabling the `Web Applet` by default" >}}.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Too many games have issues with it, it’s responsible for blocking controller input, and not many users are interested in the tutorials the service is mostly used for, so it’s a sacrifice worth the sm
```suggestion
This was necessary due to many games having issues with it. It’s responsible for blocking controller input, and not many users are interested in the tutorials the service is mostly used for, so it’s a sacrifice worth the small loss.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +{{< gh-hovercard "8120" "''Correctly adding a Signalling events on `AcquireNpadStyleSetUpdateEventHandle`" >}} makes the game playable.
```suggestion
{{< gh-hovercard "8120" "Correctly adding a Signal event on `AcquireNpadStyleSetUpdateEventHandle`" >}} makes the game playable.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +`Project Gaia` is having some minor delays caused by new additions Nintendo made on recent firmware updates.
```suggestion
`Project Gaia` is experiencing some minor delays caused by new additions Nintendo made in recent firmware updates.
```

2022-04-10 02:20 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +And on `Project Y.F.C.`, we’re measuring performance increases, as well as getting games to render for the first time:
```suggestion
And regarding `Project Y.F.C.`, we’re measuring performance increases, as well as getting games to render for the first time:
```

2022-04-10 05:56 UTC, Schplee requested changes

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +[bunnei](https://github.com/bunnei) has the highlight of this month with the {{< gh-hovercard "8050" "rewrite of the `NVFlinger` implementation" >}}, a part of `Project Y.F.C`.
```suggestion
[bunnei](https://github.com/bunnei) has the highlight of this month with the {{< gh-hovercard "8050" "rewrite of the `NVFlinger` implementation" >}}, a part of `Project Y.F.C.`.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Users with low thread CPUs could immediately tell the difference during video playbacks.
```suggestion
Users with low thread CPUs could immediately tell the difference during video playback.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +This month, we discuss an emulator inside an emulator, parts of `Project Y.F.C.` being added, graphical fixes for old and new titles, and more!
```suggestion
This month, we discuss an emulator inside an emulator, parts of Project Y.F.C. being added, graphical fixes for old and new titles, and more!
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Tagging along, a PSA for AMD users too, the currently latest 22.3.2 driver, which adds support for the `VK_KHR_workgroup_memory_explicit_layout` extension, breaks fishing in `Animal Crossing: New Hor
```suggestion
Tagging along, a PSA for AMD users too: the currently latest 22.3.2 driver, which adds support for the `VK_KHR_workgroup_memory_explicit_layout` extension, breaks fishing in `Animal Crossing: New Horizons` and can possibly make other games crash.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +`Super Mario Galaxy` uses a combination of depth buffer and stencil buffer to “see” the objects behind the star pointer used to shoot star bits.
```suggestion
`Super Mario Galaxy` uses a combination of the depth buffer and stencil buffer to “see” the objects behind the star pointer used to shoot star bits.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Our original implementation was basically guess work done back in 2018, it was lacking in *several* areas.
```suggestion
Our original implementation was basically guess work done back in 2018, and it was lacking in *several* areas.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +This is not enough to get `Hades` running. `Project Y.F.C` will take care of that in the near future, but it’s a small global performance boost that mostly benefits low-end GPUs.
```suggestion
This is not enough to get `Hades` running. `Project Y.F.C.` will take care of that in the near future, but it’s a small global performance boost that mostly benefits low-end GPUs. 
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +This most commonly affects Intel GPUs, but Vega based Radeon GPUs can also suffer from it ocasionally.
```suggestion
This most commonly affects Intel GPUs, but Vega based Radeon GPUs can also suffer from it occasionally.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Another popular reason for this issue, as mentioned in [previous reports](https://yuzu-emu.org/entry/yuzu-progress-report-dec-2021/#ui-changes) are outdated Vulkan injectors breaking support altogeth
```suggestion
Another popular reason for this issue, as mentioned in [previous reports](https://yuzu-emu.org/entry/yuzu-progress-report-dec-2021/#ui-changes), is outdated Vulkan injectors breaking support altogether.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Software like OBS Studio, OBS Streamlabs, Bandicam, Action!, Overwolf, GShade, iCUE, MSI Afterburner, *anything* with an overlay that injects into Vulkan can completely break rendering if it is outda
```suggestion
Software like OBS Studio, OBS Streamlabs, Bandicam, Action!, Overwolf, GShade, iCUE, MSI Afterburner, or *anything* with an overlay that injects into Vulkan can completely break rendering if it is outdated, or the developers don’t keep up with recent Vulkan releases.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Older hardware, for example Skylake based CPUs (gen. 10 and older) or early first and second generation Ryzen CPUs, would not only have smaller caches, but also would lack support for some instructio
```suggestion
Older hardware, for example Skylake based CPUs (gen. 10 and older) or early first and second generation Ryzen CPUs, would not only have smaller caches, but would also lack support for some instructions more modern CPUs provide.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +[Morph](https://github.com/Morph1984) {{< gh-hovercard "8041" "updated yuzu’s emulated equivalent" >}} to match the new versions, allowing games from the `Monster Hunters` series to be playable witho
```suggestion
[Morph](https://github.com/Morph1984) {{< gh-hovercard "8041" "updated yuzu’s emulated equivalent" >}} to match the new versions, allowing games from the `Monster Hunter` series to be playable without having to transfer a save file after character creation was finished.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +Can be useful for specific game settings.
```suggestion
This can be useful for game specific settings.
```

2022-04-10 05:56 UTC, Schplee commented on site/content/entry/yuzu-progress-report-mar-2022/index.md
> +This was necessary due to many games having issues with it. It’s responsible for blocking controller input, and not many users are interested in the tutorials the service is mostly used for, so it’s
```suggestion
This was necessary due to many games having issues with it. The `Web Applet` is responsible for blocking controller input, and not many users are interested in the tutorials the service is mostly used for, so it’s a sacrifice worth the small loss.
```

2022-04-10 20:47 UTC, Schplee approved these changes

2022-04-10 20:47 UTC, merged