Progress report - Arpil 2023
yuzu-emu/yuzu-emu.github.io pull request #350
Opened 2023-05-06 07:55 UTC by goldenx86

I said it was gonna be short...

2023-05-06 20:26 UTC, liamwhite commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +- Tree flickering in `The Legend of Zelda: Breath of the Wild` has been fixed on all GPU accuracy options.
Recommend moving these two later in the list

2023-05-06 20:26 UTC, liamwhite commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +The modding community requested us to allow for larger texture mods. The old 6GB limit was not enough, so byte[] {{< gh-hovercard "10035" "expanded it to support the 8GB arrangement" >}} instead, giv
```suggestion
The modding community requested us to allow for larger texture mods. The old 6GB limit was not enough, so byte[] {{< gh-hovercard "10035" "expanded it to support a custom 8GB arrangement" >}} instead, giving almost all of it to the emulated program.
```

2023-05-06 20:26 UTC, liamwhite commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +Continuing his work on improving CPU timing accuracy, [Morph](https://github.com/Morph1984) fixed confusion between the raw CPU frequency and `Counter-timer Frequency`, or CNTFRQ.
Missing a link to the PR

2023-05-06 20:26 UTC, liamwhite commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +To do so, Morph {{< gh-hovercard "10110" "disabled compute shaders" >}} entirely for Intel Windows drivers, ensuring games like `The Legend of Zelda: Breath of the Wild` can even be booted, let alone
```suggestion
To do so, Morph {{< gh-hovercard "10110" "disabled compute shaders" >}} entirely for Intel Windows drivers, ensuring games like `The Legend of Zelda: Breath of the Wild` can still boot―even though they'll have gameplay issues as a result.
```

2023-05-10 07:17 UTC, Schplee requested changes

2023-05-10 07:17 UTC, Schplee commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +- And much, much more!.
```suggestion
- And much, much more!
```

2023-05-10 07:17 UTC, Schplee commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +[twitchax](https://github.com/twitchax) knows that for certain hosting servers, such as `fly.io`, a {{< gh-hovercard "10068" "custom bind address" >}} is needed.
```suggestion
[twitchax](https://github.com/twitchax) knows that for certain server hosts, such as `fly.io`, a {{< gh-hovercard "10068" "custom bind address" >}} is needed.
```

2023-05-10 07:17 UTC, Schplee commented on site/content/entry/yuzu-progress-report-apr-2023/index.md
> +You will of course need HDR output enabled in both your display’s and Windows 11’s settings.
```suggestion
You will of course need HDR output enabled in both your display’s and Windows 11 settings.
```

2023-05-10 19:30 UTC, merged