Progress report December 2023
yuzu-emu/yuzu-emu.github.io pull request #386
Opened 2024-01-06 21:33 UTC by goldenx86

Too long

2024-01-07 02:21 UTC, FearlessTobi reviewed
great stuff, I only did a very quick glance at the report though

2024-01-07 02:21 UTC, FearlessTobi commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +- And a Start button, which allows you to select global or custom configuration. Launching from the game list will always load the custom configuration.
"which allows you to select **a** global or custom configuration" ?

2024-01-07 02:21 UTC, FearlessTobi commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +To work around this limitation, byte[] {{< gh-hovercard "12466" "inserts a layer" >}} between the software page table and the host mapping system, constantly tracking the heap allocations made by pro
```suggestion
To work around this limitation, byte[] {{< gh-hovercard "12466" "inserts a layer" >}} between the software page table and the host mapping system, constantly tracking the heap allocations made by programs and automatically recycling some less recently used mappings, which causes some stuttering―but is better than a game crash. Collection will reduce the number of mappings to around half of the 65530 limit most systems ship with.
```

2024-01-07 02:21 UTC, FearlessTobi commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +byte[] refactored how yuzu emulates {{< gh-hovercard "12236" "CPU core activation," >}} he assures us writing three thousand lines of code simplifies the design of the ARM interface the emulator uses
I do not understand this sentence

2024-01-09 11:50 UTC, Schplee requested changes

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +The first part finished is the {{< gh-hovercard "12289" "emulation" >}} of `AppletResource`, which allows the developers to start working on multiprocess support in the near future, as well as other
```suggestion
The first part finished is the {{< gh-hovercard "12289" "emulation" >}} of `AppletResource`, which allows the developers to start working on multiprocess support in the near future, as well as other necessary resources like `AppletResourceUserId`, or simply `aruid`.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +	"./batman.png|The Goddamn Batman (Batman: Arkham Knight)"
```suggestion
	"./batman.png|The Batman (Batman: Arkham Knight)"
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +An entire service needed some patching-up, specifically, `ro`, or {{< gh-hovercard "12321" "relocatable object" >}} (allowing programs to load libraries on the fly), needed to be rewritten a bit–just
```suggestion
An entire service needed some patching-up, specifically, `ro`, or {{< gh-hovercard "12321" "relocatable object" >}} (allowing programs to load libraries on the fly), needed to be rewritten a bit  — just over a thousand lines of code.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +The appId window property is intended to match the name of the `.desktop` file, for example, `org.yuzu_emu.yuzu.desktop`.
```suggestion
The `appId` window property is intended to match the name of the `.desktop` file, for example, `org.yuzu_emu.yuzu.desktop`.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Plasma desktop by default sets this property to the name of the binary file, which in this case is just `yuzu`, and doesn’t match the expected value of `org.yuzu_emu.yuzu`.
```suggestion
Plasma desktop, by default, sets this property to the name of the binary file, which in this case is just `yuzu`, and doesn’t match the expected value of `org.yuzu_emu.yuzu`.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Not much to mention this time, but there’s a few nits that deserve to be brought up.
```suggestion
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +What’s this? A free and open source Mesa Vulkan driver for Turing and later NVIDIA hardware, that’s what it is!
```suggestion
What’s this? A free and open source Mesa Vulkan driver for Turing and later NVIDIA hardware?
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +2024 is the year of ~~the Linux desktop~~ working Intel Windows drivers.
```suggestion
In contrast, Intel failed us again. 
No word on the fix for the geometry shader crash we [reported](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/551) back in October yet.

We hope it’s just a delay from the holidays.
2024 is the year of ~~the Linux desktop~~ working Intel Windows drivers.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +This section needs to be split too. Just a moment.
```suggestion
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Much better.
```suggestion
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +In simpler terms, Balanced mode in the Red Magic 9 is faster than Diablo mode in the previous Red Magic 8.
```suggestion
In short, Balanced mode in the Red Magic 9 is faster than Diablo mode in the previous Red Magic 8.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Current [releases](https://github.com/K11MCH1/AdrenoToolsDrivers/releases) for example have added support for rare GPU variants, like Adreno 642L and Adreno 644.
```suggestion
Current [releases](https://github.com/K11MCH1/AdrenoToolsDrivers/releases) have added support for rare GPU variants, like Adreno 642L and Adreno 644.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Performance has improved too, as well as stability.
```suggestion
Performance and stability have improved as well.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Keep up to date with Turnip releases; they usually only bring benefits.
```suggestion
Keep up to date with Turnip releases; they usually only bring improvements.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +This means in the future Mali moments will maybe stop existing, in a similar way to how Turnip provides a much better experience to Adreno users.
```suggestion
This means that Mail moments may cease existing sometime in the future, in a similar way to how Turnip provides a much better experience to Adreno users.
```

2024-01-09 11:50 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +That’s all folks! I’m finishing writing and collecting media at 7AM. Thank you for reading until the end, let’s see you all again next time in the first progress report of 2024!
```suggestion
That’s all folks! Thank you for reading until the end, we hope to see you all again in the first progress report of 2024!
```

2024-01-10 04:24 UTC, Schplee requested changes

2024-01-10 04:24 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +This means that Mail moments may cease existing sometime in the future, in a similar way to how Turnip provides a much better experience to Adreno users.
```suggestion
This means that Mali moments may cease existing sometime in the future, in a similar way to how Turnip provides a much better experience to Adreno users.
```

2024-01-10 04:24 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +While this isn’t normally an issue on desktop, especially for users that don’t enable Asynchronous Presentation (available in `Emulation > Configure… > Graphics > Advanced`), Android, a platform that
```suggestion
While this isn’t normally an issue on desktop, especially for users that don’t enable Asynchronous Presentation (available in `Emulation > Configure… > Graphics > Advanced`), Android, a platform that demands always using asynchronous presentation, showed us that low enough performance with the setting toggled on, regardless of OS or platform, can cause the queue of swapchain images to grow beyond the limit of 6 frames. Thus, leading to a driver crash and your progress being lost. Ouch.
```

2024-01-10 04:24 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Even Turnip, with its [early support](https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v24.0.0_R15) already shows outstanding results, here is an Adreno 740 vs an Adreno 750:
```suggestion
Even Turnip, with its [early support](https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v24.0.0_R15) already shows outstanding results. Here is an Adreno 740 vs an Adreno 750:
```

2024-01-10 04:24 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +	"i9 14900K who? (The Legend of Zelda: Breath of the Wild)"
```suggestion
	"i9-14900K who? (The Legend of Zelda: Breath of the Wild)"
```

2024-01-10 04:24 UTC, Schplee commented on site/content/entry/yuzu-progress-report-dec-2023/index.md
> +Another win for OpenGL users is two fixes for `Xenoblade Chronicles 3`.
```suggestion
OpenGL users saw another win with the implementation of two fixes for `Xenoblade Chronicles 3`.
```

2024-01-10 21:00 UTC, merged